config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  resources :notifications
  resources :comments
  get 'events/index'
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'
  devise_for :users
  mount ActionCable.server => '/cable'
  #devise_for :user, controllers: { sessions: 'users/sessions' }
  #get 'dashboard/index'
  #get '/registration/index', to: 'registration#index'
  #get 'signup' => 'registration#signup'
  #get 'new' => 'registration#new'
  #post 'login' => 'registration#login'
  
  #post "create"  => "registration#create"
  #devise_scope :user do
   # root to: 'devise/sessions#new'
  #end
  #devise_scope :users do
   # get '/users/sign_out' => 'devise/sessions#destroy'
  #end
  #get 'users(.:format)' => 'devise/registrations#show'
  get '/search' => 'pages#search', :as => 'search_page'
  #get 'carts/:id' => "carts#show", as: "cart"
  #delete 'carts/:id' => "carts#destroy"
  resources :carts
  resources :cart_items
  post 'cart_items/:id/add' => "cart_items#add_quantity", as: "cart_item_add"
  post 'cart_items/:id/reduce' => "cart_items#reduce_quantity", as: "cart_item_reduce"
  
  #post 'cart_items' => "cart_items#create"
  #get 'cart_items/:id' => "cart_items#show", as: "cart_item"
  #delete 'cart_items/:id' => "cart_items#destroy"
  resources :products do
    collection { post :import }
  end
  get '/secret', to: 'pages#secret', as: :secret
  root 'dashboard#index'
  resources :orders
  get 'notification/index'
  resources :order_items
  #post 'order_items' => "order_items#create"
  #get 'order_items' => "order_items#index", as: "order_item"
  resources :shipping_addresses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :products
  validates :user_id, uniqueness: true
  def sub_total
    sum = 0
    self.cart_items.each do |cart_item|
      sum+= cart_item.total_price
    end
    return sum
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :product
    belongs_to :cart
  def total_price
    self.quantity * self.product.price
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  after_create_commit { create_event }

  private
    def create_event
      Event.create message: "A new comment has been created"
    end
end

app/models/event.rb
class Event < ApplicationRecord
    after_create_commit { EventBroadcastJob.perform_later self }
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
 belongs_to :user
 belongs_to :location, optional: true
 has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
 belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  # belongs_to :product_category
  
  validates :price, :description, :product_name, presence: true
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_one_attached :image
  def self.to_csv
    attributes = %w{id price description product_name}
      CSV.generate(headers: true) do |csv|
        csv << attributes
  
        all.find_each do |product|
          csv << attributes.map{ |attr| product.send(attr) }
        end
      end
  end

  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      product = find_by_id(row["id"]) || new
      product.attributes = row.to_hash.slice(*accessible_attributes)
      product.save!
    end
  end
  
  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when '.csv' then Roo::Csv.new(file.path, nil, :ignore) 
    when ".xls" then Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end
  
   
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  has_many :products
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
   validates :pincode, :address, :locality, :save_address_as, presence: true
   validates :pincode, length: { is: 6 }
   belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, presence: true
  has_many :products
  has_many :shipping_addresses
  has_one :cart  
  has_one_attached :avatar
  after_create :send_mail
  def send_mail
    UserMailer.send_enabled_message(self).deliver
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def show
      @cart = @current_cart
    end
    
    def destroy
      @cart = @current_cart
      @cart.destroy
      session[:cart_id] = nil
      redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/show.html.erb
<h2>Cart show</h2>
<% if current_user %>
<ul>
  
  <% if @cart.cart_items.size == 0 %>
     <h5>please add product</h5>
  <% else%>
  <% @cart.cart_items.each do |cart_item| %>
    <div class="container">
      <div class="row">
      <div class="col-sm-7 x" style="background-color:lavender;">
        <h1 align="center"><%= cart_item.product.product_name %></h1>
        <div class="col-sm-5" style="background-color:lavenderblush;">
          <%if cart_item.product.image.attached? %>
            <%= image_tag cart_item.product.image, size: "150x100"%>
          <%end%>
          </div>
        <h5>Price:<%= cart_item.product.price%></h5>
        <h5>Description:<%= cart_item.product.description%></h5>
        <h5>Quantity:<%= cart_item.quantity%></h5>
        <h5>Total Price: <%= cart_item.total_price %><h5>
        
        <%= link_to "Add one", cart_item_add_path(:id => cart_item), method: :post %>tio
        <%= link_to "Reduce one", cart_item_reduce_path(:id => cart_item), method: :post %>
        <%= link_to "Remove item", cart_item_path(cart_item), method: :delete %>
      
      </div>
      </div>
    </div>
  <% end %>
  
</ul>

<h3>Sub total: <%= (@cart.sub_total) %></h3>
<%= link_to "Proceed to checkout", shipping_addresses_path %><br>
<%= link_to "Empty cart", cart_path(@current_cart),method: :delete, data: {confirm: "Are you sure?"}%>
<% end %>
<% else %>
<h5> first login to add item in bag </h5>
<%= link_to "login", new_user_session_path %><br>
<% end %>

<style >
.x{
text-align: left;
}
</style>