config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  resources :notifications
  resources :comments
  get 'events/index'
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'
  devise_for :users
  mount ActionCable.server => '/cable'
  #devise_for :user, controllers: { sessions: 'users/sessions' }
  #get 'dashboard/index'
  #get '/registration/index', to: 'registration#index'
  #get 'signup' => 'registration#signup'
  #get 'new' => 'registration#new'
  #post 'login' => 'registration#login'
  
  #post "create"  => "registration#create"
  #devise_scope :user do
   # root to: 'devise/sessions#new'
  #end
  #devise_scope :users do
   # get '/users/sign_out' => 'devise/sessions#destroy'
  #end
  #get 'users(.:format)' => 'devise/registrations#show'
  get '/search' => 'pages#search', :as => 'search_page'
  #get 'carts/:id' => "carts#show", as: "cart"
  #delete 'carts/:id' => "carts#destroy"
  resources :carts
  resources :cart_items
  post 'cart_items/:id/add' => "cart_items#add_quantity", as: "cart_item_add"
  post 'cart_items/:id/reduce' => "cart_items#reduce_quantity", as: "cart_item_reduce"
  
  #post 'cart_items' => "cart_items#create"
  #get 'cart_items/:id' => "cart_items#show", as: "cart_item"
  #delete 'cart_items/:id' => "cart_items#destroy"
  resources :products do
    collection { post :import }
  end
  get '/secret', to: 'pages#secret', as: :secret
  root 'dashboard#index'
  resources :orders
  get 'notification/index'
  resources :order_items
  #post 'order_items' => "order_items#create"
  #get 'order_items' => "order_items#index", as: "order_item"
  resources :shipping_addresses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :products
  validates :user_id, uniqueness: true
  def sub_total
    sum = 0
    self.cart_items.each do |cart_item|
      sum+= cart_item.total_price
    end
    return sum
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :product
    belongs_to :cart
  def total_price
    self.quantity * self.product.price
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  after_create_commit { create_event }

  private
    def create_event
      Event.create message: "A new comment has been created"
    end
end

app/models/event.rb
class Event < ApplicationRecord
    after_create_commit { EventBroadcastJob.perform_later self }
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
 belongs_to :user
 belongs_to :location, optional: true
 has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
 belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  # belongs_to :product_category
  
  validates :price, :description, :product_name, presence: true
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_one_attached :image
  def self.to_csv
    attributes = %w{id price description product_name}
      CSV.generate(headers: true) do |csv|
        csv << attributes
  
        all.find_each do |product|
          csv << attributes.map{ |attr| product.send(attr) }
        end
      end
  end

  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      product = find_by_id(row["id"]) || new
      product.attributes = row.to_hash.slice(*accessible_attributes)
      product.save!
    end
  end
  
  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when '.csv' then Roo::Csv.new(file.path, nil, :ignore) 
    when ".xls" then Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end
  
   
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  has_many :products
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
   validates :pincode, :address, :locality, :save_address_as, presence: true
   validates :pincode, length: { is: 6 }
   belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, presence: true
  has_many :products
  has_many :shipping_addresses
  has_one :cart  
  has_one_attached :avatar
  after_create :send_mail
  def send_mail
    UserMailer.send_enabled_message(self).deliver
  end
end

app/controllers/shipping_addresses_controller.rb
class ShippingAddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]
  def new
    @shipping_address = ShippingAddress.new
  end
  def index
    @shipping_address = ShippingAddress.all
  end
  def create
    @shipping_address = current_user.shipping_addresses.create(:pincode => address_params[:pincode],:address => address_params[:address],:locality => address_params[:locality],:save_address_as => address_params[:save_address_as])
    if @shipping_address.valid?
      @shipping_address.save
      render 'orders/index'
    else
      flash[:notice] = "You have not properly fill all the coloumns"
      render 'shipping_addresses/new'
    end
  end
  def edit
    
  end
  def destroy
    @shipping_address.destroy
    flash[:notice] = "Address was successfully destroyed." 
    redirect_to orders_path
  end
  def update
    if @shipping_address.update(address_params)
      redirect_to orders_path
    else    
      render 'edit'
    end
  end

private
  
  def set_address
    @shipping_address = ShippingAddress.find(params[:id])
  end

  def address_params
    params.require(:shipping_address).permit(:pincode, :address, :locality, :save_address_as)
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shipping_addresses_helper.rb
module ShippingAddressesHelper
end

app/views/shipping_addresses/edit.html.erb
<%= form_for @shipping_address do |f| %>
    <p>
      <%= f.label :pincode %><br>
      <%= f.text_field :pincode, required: true, autofocus: true %>
    </p>
    <p>
      <%= f.label :address %><br>
      <%= f.text_area :address %>
    </p>
    <p>
      <%= f.label :locality %><br>
      <%= f.text_area :locality %>
    </p>

    <p>
    <%= f.label :save_address_as %><br>
    <%= f.radio_button :save_address_as, 'home', :checked => true %> 
    <%= f.label  :save_address_as_home, 'Home' %>
    <%= f.radio_button :save_address_as, 'office' %>f
    <%= f.label :save_address_as_office, 'Office' %><br>
    </p>

    <p>
      <%= f.submit %>
    </p>
  <% end%>

app/views/shipping_addresses/index.html.erb
<h2>All Address</h2>

<% ShippingAddress.where(user_id: current_user.id).all.each do |address1| %>
  <p>pincode: <%= address1.pincode %></p>
  <p>address: <%= address1.address %></p>
  <p>locality: <%= address1.locality %></p>
  <p>type: <%= address1.save_address_as %></p>
  <%= link_to 'Edit ', edit_shipping_address_path(address1), :class => "btn btn-primary" %><br>

  <%= link_to ' Destroy', shipping_address_path(address1), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-secondary" %>
  <div class="checkbox">
  <label><input type="checkbox" value="">choose address/<label>
</div>
<% end %>

<%= button_to "Add address", new_shipping_address_path, method: :get %>
<ul>
  <% @current_cart.cart_items.each do |cart_item| %>
    <div class="container">
      <div class="row">
      <div class="col-sm-7 x" style="background-color:lavender;">
        <h1 align="center"><%= cart_item.product.product_name %></h1>
        <div class="col-sm-7 x" style="background-color:lavender;">
        <h1 align="center"><%= cart_item.product.product_name %></h1>
        <div class="col-sm-5" style="background-color:lavenderblush;">
          <%if cart_item.product.image.attached? %>
            <%= image_tag cart_item.product.image, size: "150x100"%>
          <%end%>
          </div>
        <h5>Price:<%= cart_item.product.price%></h5>
        <h5>Description:<%= cart_item.product.description%></h5>
        <h5>Quantity:<%= cart_item.quantity%></h5>
        <h5>Total Price: <%= cart_item.total_price %>
        
        <%= link_to "Add one", cart_item_add_path(:id => cart_item), method: :post %>
        <%= link_to "Reduce one", cart_item_reduce_path(:id => cart_item), method: :post %>
        <%= link_to "Remove item", cart_item_path(cart_item), method: :delete %>
      
      </div>
      </div>
    </div>
    
    
    
  <% end %>
</ul>

<h3>Sub total: <%= (@current_cart.sub_total) %></h3>
<%= link_to "Proceed to order", orders_show_path, data: {confirm: "Are you sure?"}%><br>
<%= link_to "Empty cart", cart_path(@current_cart),method: :delete, data: {confirm: "Are you sure?"}%>


<style >
.x{
text-align: left;
}
</style>

app/views/shipping_addresses/new.html.erb
<%= form_for @shipping_address do |f| %>
    <p>
      <%= f.label :pincode %><br>
      <%= f.text_field :pincode, required: true, autofocus: true %>
    </p>
    <p>
      <%= f.label :address %><br>
      <%= f.text_area :address %>
    </p>
    <p>
      <%= f.label :locality %><br>
      <%= f.text_area :locality %>
    </p>

    <p>
    <%= f.label :save_address_as %><br>
    <%= f.radio_button :save_address_as, 'home', :checked => true %> 
    <%= f.label  :save_address_as_home, 'Home' %>
    <%= f.radio_button :save_address_as, 'office' %>f
    <%= f.label :save_address_as_office, 'Office' %><br>
    </p>

    <p>
      <%= f.submit %>
    </p>
  <% end%>