config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  resources :notifications
  resources :comments
  get 'events/index'
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'
  devise_for :users
  mount ActionCable.server => '/cable'
  #devise_for :user, controllers: { sessions: 'users/sessions' }
  #get 'dashboard/index'
  #get '/registration/index', to: 'registration#index'
  #get 'signup' => 'registration#signup'
  #get 'new' => 'registration#new'
  #post 'login' => 'registration#login'
  
  #post "create"  => "registration#create"
  #devise_scope :user do
   # root to: 'devise/sessions#new'
  #end
  #devise_scope :users do
   # get '/users/sign_out' => 'devise/sessions#destroy'
  #end
  #get 'users(.:format)' => 'devise/registrations#show'
  get '/search' => 'pages#search', :as => 'search_page'
  #get 'carts/:id' => "carts#show", as: "cart"
  #delete 'carts/:id' => "carts#destroy"
  resources :carts
  resources :cart_items
  post 'cart_items/:id/add' => "cart_items#add_quantity", as: "cart_item_add"
  post 'cart_items/:id/reduce' => "cart_items#reduce_quantity", as: "cart_item_reduce"
  
  #post 'cart_items' => "cart_items#create"
  #get 'cart_items/:id' => "cart_items#show", as: "cart_item"
  #delete 'cart_items/:id' => "cart_items#destroy"
  resources :products do
    collection { post :import }
  end
  get '/secret', to: 'pages#secret', as: :secret
  root 'dashboard#index'
  resources :orders
  get 'notification/index'
  resources :order_items
  #post 'order_items' => "order_items#create"
  #get 'order_items' => "order_items#index", as: "order_item"
  resources :shipping_addresses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :products
  validates :user_id, uniqueness: true
  def sub_total
    sum = 0
    self.cart_items.each do |cart_item|
      sum+= cart_item.total_price
    end
    return sum
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :product
    belongs_to :cart
  def total_price
    self.quantity * self.product.price
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  after_create_commit { create_event }

  private
    def create_event
      Event.create message: "A new comment has been created"
    end
end

app/models/event.rb
class Event < ApplicationRecord
    after_create_commit { EventBroadcastJob.perform_later self }
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
 belongs_to :user
 belongs_to :location, optional: true
 has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
 belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  # belongs_to :product_category
  
  validates :price, :description, :product_name, presence: true
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_one_attached :image
  def self.to_csv
    attributes = %w{id price description product_name}
      CSV.generate(headers: true) do |csv|
        csv << attributes
  
        all.find_each do |product|
          csv << attributes.map{ |attr| product.send(attr) }
        end
      end
  end

  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      product = find_by_id(row["id"]) || new
      product.attributes = row.to_hash.slice(*accessible_attributes)
      product.save!
    end
  end
  
  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when '.csv' then Roo::Csv.new(file.path, nil, :ignore) 
    when ".xls" then Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end
  
   
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  has_many :products
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
   validates :pincode, :address, :locality, :save_address_as, presence: true
   validates :pincode, length: { is: 6 }
   belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, presence: true
  has_many :products
  has_many :shipping_addresses
  has_one :cart  
  has_one_attached :avatar
  after_create :send_mail
  def send_mail
    UserMailer.send_enabled_message(self).deliver
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_sidenav.html.erb
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

<div class="nav-side-menu p-3 mb-2 bg-light text-dark">
    <div class="brand"></div>
    <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>
  
        <div class="menu-list">
  
            <ul id="menu-content" class="menu-content collapse out">
                <li>
                  <a href="#">
                  <i class="fa fa-dashboard fa-lg"></i> Dashboard
                  </a>
                </li>

                <li  data-toggle="collapse" data-target="#products" class="collapsed active">
                  <a href="#"><i class="fa fa-gift fa-lg"></i> ..... <span class="arrow"></span></a>
                </li>
                <ul class="sub-menu collapse" id="products">
                    <li class="active"><a href="#">RFT-H1</a></li>
                    <li><a href="#">....</a></li>
                    <li><a href="#">...</a></li>
                    <li><a href="#">...</a></li>
                </ul>


                <li data-toggle="collapse" data-target="#service" class="collapsed">
                  <a href="#"><i class="fa fa-globe fa-lg"></i> ......<span class="arrow"></span></a>
                </li>  
                <ul class="sub-menu collapse" id="service">
                  <li>....</li>
                  <li>....</li>
                  <li>....</li>
                </ul>


                <li data-toggle="collapse" data-target="#new" class="collapsed">
                  <a href="#"><i class="fa fa-car fa-lg"></i>.....<span class="arrow"></span></a>
                </li>
                <ul class="sub-menu collapse" id="new">
                  <li>.....</li>
                  <li>.....</li>
                </ul>


                 <li>
                  <a href="#">
                  <i class="fa fa-user fa-lg"></i> .......
                  </a>
                  </li>

                 <li data-toggle="collapse" data-target="#new" class="collapsed">
                  <a href="#"><i class="fa fa-car fa-lg"></i>.... <span class="arrow"></span></a>
                </li>
                <ul class="sub-menu collapse" id="new">
                  <li>.....</li>
                  <li>.....</li>
                </ul>

            </ul>
     </div>

app/views/layouts/_topnav.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container">
        <div class="collapse navbar-collapse justify-content-end" id="navbarsExampleDefault">
            <ul class="navbar-nav m-auto">
                <li class="nav-item">
                    <a class="nav-link"  href="">Home</a>
                </li>
            </ul>
            

            <%= form_tag(search_page_path, :method => "get",   
    class: 'navbar-form navbar-left') do %>  
  <div class="input-group">  
    <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
    <div class="input-group-btn">  
      <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
    </div>  
  </div>  
<% end %>
</form>
            <% if current_user %>
            
            

              <ul class="navbar-nav m-auto">
                <li class="nav-item">
                <div class="nav-link">Notifications (<b id="notifications-count">2</b>)</div>
                <div class="col-md-6 col-sm-6 col-xs-6 text-right">
                <div class="col-md-6 col-sm-6 col-xs-6 text-right">
                <a href="notifications#index" class="rIcon allRead" data-tooltip="tooltip" data-placement="bottom" title="tümü okundu."><i class="fa fa-dot-circle-o"></i></a>
              </div></div>
                </li>
        
     
                  <li><a class="nav-link"  href="users/edit">Edit Profile</a></li>

                  <%if current_user.role == "customer" %>
                  <li class="nav-item">
                  <a class="btn btn-success btn-sm ml-3" href="carts/index">
                    <i class="fa fa-shopping-cart"></i> Cart
                    <span class="badge badge-light"></span>
                    </a></li>

                    <li><a class="navbar-brand" href="users/show">Profile</a>
                     <button class="navbar-toggler" type="button data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                     <span class="navbar-toggler-icon"></span>
                    </button></li>

                    <%= link_to "order details", order_items_path, method: :get %></br>
                    <%= link_to "Sign out", destroy_user_session_path, method: :delete%>
                  <% end %>
                  <% if current_user.role == "admin"%>
                    
                    <li class="nav-item">
                      <a class="nav-link"  href="products">ProductList</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link"  href="products/new">Add Product</a>
                    </li> 
                    <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
                 
                       
                  <% end %>
                  <% if current_user.role == "seller"%>
                  <li class="nav-item">
                  <a class="nav-link"  href="products">ProductList</a>
              </li>
              <li class="nav-item">
              <a class="nav-link"  href="products/new">Add Product</a>
          </li> 
        
          <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
         
          <% end %>
          <li><%if current_user.avatar.attached? %>
          <img src = "<%= (url_for(current_user.avatar)) %>" alt = "no profile photo" width="12%">
        <%end%></li>

             <% else %>
                <li class="nav-item">
                <a class="nav-link" href="users/sign_up">Sign up</a>
                   
                </li>
                <li class="nav-item">
                <a class="nav-link" href="users/sign_in">login</a>
                </li>                                    

            
            <% end %>
        </div>
    </div>
</nav>
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">E-COMMERCE PRODUCT</h1>
         </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CartApp</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      <%= javascript_pack_tag 'application' %>
      <link href="css/main.css" rel="stylesheet" media="all">
   </head>

  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>
  </div>
  
  <body> 
    <% if params[:controller] == "dashboard" %>
      <%= render partial: "layouts/topnav" %>
      <%= render partial: "layouts/sidenav"%>
    <% end %>
    <%= yield %>
    
    </div>
    <footer align="center">
        <p>&copy; Company 2020</p>
      </footer>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to '', controller: 'products' %>